dist: precise
sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
env:
  - CAMUNDA=LATEST
  - CAMUNDA=RELEASE
  - CAMUNDA=7.12.0
  - CAMUNDA=7.11.0
  - CAMUNDA=7.10.0
  - CAMUNDA=7.9.0
  - CAMUNDA=7.8.0
  - CAMUNDA=7.7.0
  - CAMUNDA=7.6.0
  - CAMUNDA=7.5.0
  - CAMUNDA=7.4.0
  - CAMUNDA=7.3.0
  - CAMUNDA=7.2.0
  - CAMUNDA=7.1.0-Final
  - CAMUNDA=7.0.0-Final  
install: true
script: mvn -Dcamunda-bpm.version=$CAMUNDA
